/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.util.ArrayList;
import java.util.List;
import modelos.Questao;

/**
 *
 * @author aluno
 */
public class TelaJogo extends javax.swing.JFrame {
    
    private List<Questao> questoes = new ArrayList<>();
    
    private int indexQuestaoAtual = 0;
    
    private Questao questao;

    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();
    }
    
    public TelaJogo(List<Questao> listQuestoes){
        
        initComponents();        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTextAreaQuestao = new javax.swing.JTextArea();
        jRadioButtonResposta0 = new javax.swing.JRadioButton();
        jRadioButtonResposta1 = new javax.swing.JRadioButton();
        jRadioButtonResposta2 = new javax.swing.JRadioButton();
        jRadioButtonResposta3 = new javax.swing.JRadioButton();
        jLabelQuestao = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jButtonProsseguir = new javax.swing.JButton();
        jButtonFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaQuestao.setEditable(false);
        jTextAreaQuestao.setColumns(20);
        jTextAreaQuestao.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jTextAreaQuestao.setRows(5);
        jTextAreaQuestao.setText("Pergunta?");
        jScrollPane.setViewportView(jTextAreaQuestao);

        jRadioButtonResposta0.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jRadioButtonResposta0.setText(" ");

        jRadioButtonResposta1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jRadioButtonResposta1.setText(" ");
        jRadioButtonResposta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonResposta1ActionPerformed(evt);
            }
        });

        jRadioButtonResposta2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jRadioButtonResposta2.setText(" ");
        jRadioButtonResposta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonResposta2ActionPerformed(evt);
            }
        });

        jRadioButtonResposta3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jRadioButtonResposta3.setText(" ");

        jLabelQuestao.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelQuestao.setText("Questão");

        jLabelNumero.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelNumero.setText("X");

        jButtonProsseguir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/prosseguir.png"))); // NOI18N

        jButtonFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/confirmar.png"))); // NOI18N
        jButtonFinalizar.setEnabled(false);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonResposta3)
                            .addComponent(jRadioButtonResposta2)
                            .addComponent(jRadioButtonResposta0)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabelQuestao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNumero))
                            .addComponent(jRadioButtonResposta1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jButtonProsseguir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFinalizar)))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuestao)
                    .addComponent(jLabelNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonResposta0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonResposta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonResposta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonResposta3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonProsseguir)
                    .addComponent(jButtonFinalizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonResposta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonResposta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonResposta2ActionPerformed

    private void jRadioButtonResposta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonResposta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonResposta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JButton jButtonProsseguir;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelQuestao;
    private javax.swing.JPanel jPanel;
    private javax.swing.JRadioButton jRadioButtonResposta0;
    private javax.swing.JRadioButton jRadioButtonResposta1;
    private javax.swing.JRadioButton jRadioButtonResposta2;
    private javax.swing.JRadioButton jRadioButtonResposta3;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea jTextAreaQuestao;
    // End of variables declaration//GEN-END:variables

    private void updateTela(){
        
            questao = questoes.get(indexQuestaoAtual);
            
            jTextAreaQuestao.setText(questao.getEnunciado());
            
            jRadioButtonResposta0.setText(questao.getRespostas().get(0));
            
            jRadioButtonResposta1.setText(questao.getRespostas().get(1));
            
            jRadioButtonResposta2.setText(questao.getRespostas().get(2));
            
            jRadioButtonResposta3.setText(questao.getRespostas().get(3));
            
            jLabelNumero.setText(String.valueOf(indexQuestaoAtual+1));
        
    }

}
